### ISSUE TITLE
Allow for local config settings

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/patron-groups#2]
If I'm reading the documentation correctly -- and I haven't tried to run it yet -- to get settings like the password to petl I'd have to either edit the config, which I might then accidentally commit, or I'd have to specify on the command line. Maybe we could have a gitignored petl.local.ini or somesuch to mitigate that.

Or maybe I'm reading it wrong. :-) @mgsimpson-ua

**Comment by ghost** [comment]
I was thinking about forcing everyone to always specify passwords on the command line. :)

But now that you mention it, petl.local.ini sounds like a good idea.

**Comment by ghost** [comment]
Although now I'm thinking about how much logic I'd have to add to the "petl" script (multiple config files specified, ordering of overrides per-file and per-section, etc.) and I'm quailing. :)

**Comment by michaelhagedon** [comment]
@mgsimpson-ua Declining is OK, too. :-)

**Comment by ghost** [comment]
Gonna decline, going with CLI parameter and/or environment variables for overrides for now.

**Comment by astrochun** [comment]
Going to revisit this issue soon and let you know what makes sense.  When I was perusing petl (or is it petal) I had thought access with via a local configuration.
