### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by ghost** [ualibraries/patron-groups#6]
Do a round of dependency updates -- mainly "requirements.txt" on the Python side, and updating to latest-version Alpine Linux base container in "Dockerfile".

**Comment by ghost** [comment]
Hey Mike H., under proper semantic versioning, if I change underlying dependencies without otherwise affecting the code, what level bump is that? Minor version number? Feels like more than a patch number bump, but less than a major version bump.

**Comment by michaelhagedon** [comment]
IMO, semantic versioning gets a bit more subjective when we're not developing APIs that have the concerns of backward compatibility or deprecation for example. For a command-line tool, I'd say the CLI flags and switches are equivalent in this case. So if there's no impact on the person running the command, I might be comfortable with a patch/point release. If there is some effect, maybe a minor version. But I don't have strong feelings on that. :-)

**Comment by ghost** [comment]
Updated all dependencies I could find (on both Docker and Python sides) to current versions for v1.5.0 release.
